apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: webapp
    image: yaosiangsu/k8s4devs-webapp:v0.4
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 3
